#!/usr/bin/python

import socket, ipaddress, time
from termcolor import colored

startTime = time.time()

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.setdefaulttimeout(15)

try:
    host = input("Enter the IP address to scan: ")
    ip = ipaddress.ip_address(host)
    print(f'{ip} is correct. Version: IPv{ip.version}')
except ValueError:
    print("Address is invalid, please try again.")

def portscanner(port):
    if sock.connect_ex((host,port)):
        print(colored("[**] Port %d is closed [**]" % (port), 'yellow'))
    else:
        print(colored("[>>>] Port %d is open [<<<]" % (port), "green"))
print("Time taken:", time.time() - startTime)

for port in range(100):
    portscanner(port)
